### ISSUE TITLE
Core game system milestone

### ISSUE THREAD

**Issue by mikewesthad** [retwedt/octo-chainsaw#2]
### Essentials

- [ ] Combo-based system, which gives bonuses to speed || attack || score.
- [ ] Wave progression, ramp challenge up as time passes
- [ ] Multiple crowd movement patterns (flocking, dashing, fleeing, etc.)
- [ ] Multiple player attacks that have different areas of effect (long range straight line, close range arc, etc.)
